# version: "3.8"
services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      #- HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      #- MONGO_URI=${MONGO_URI}
      #- MEILI_HOST=${MEILI_HOST}
      #- RAG_PORT=${RAG_PORT:-8000}
      #- RAG_API_URL=${RAG_API_URL}
    volumes:
      #- ./librechat.yaml:/app/librechat.yaml 
      - /home/lewy/apps/LibreChat/librechat.yaml:/app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
    networks:
      - proxy-network
      - app-network
      
  # client:
  #   image: nginx:1.27.0-alpine
  #   container_name: LibreChat-NGINX
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - api
  #   restart: always
  #   volumes:
  #     - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
    networks:
      - app-network

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      #- MEILI_HOST=${MEILI_HOST}
      #- MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
    volumes:
      - ./meili_data_v1.7:/meili_data
    networks:
      - app-network

  vectordb:
    image: ankane/pgvector:latest
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - app-network
      
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - app-network

volumes:
  pgdata2:

networks:
  app-network:
    name: librechat-network
  proxy-network:
    external: true
